on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Test
        run: go test ./...
